# This is a basic workflow to help you get started with Actions

name: CI to Docker Hub

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checamos el repo
        uses: actions/checkout@v2

      # Login a Docker
      - name: Login a docker
        uses: docker/login-action@v1
        with: 
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCEESS_TOKEN}}

      # SetUp del Buildx
      - name: Configuramos el Docker Buildx
        id: biuldx
        uses: docker/setup-buildx-action@v1
        
      - name: Construir y empujar (build and push)
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME}}/psweb:latest
      
      - name: Image digest
        run: echo ${{ secrets.docker_build.outputs.digest }}
          
          
